### ISSUE TITLE
deno Unexpected exit

### ISSUE THREAD

**Issue by blogwy** [eliassjogreen/deno_webview#32] opened 2020-06-04 08:40 UTC
deno : 1.0.4
command:
```
deno run -A -r --unstable --allow-read webview.ts
```
code:
```
import { WebView } from "https://deno.land/x/webview/mod.ts";

const html = (n: number) =>
  `
  <html>
  <body>
    <h1>${n}</h1>
  </body>
  </html>
`;

const webview1 = new WebView({
  title: "Multiple deno_webview example",
  url: `data:text/html,${encodeURIComponent(html(1))}`,
  width: 400,
  height: 200,
  resizable: true,
  debug: true,
  frameless: false,
});

const webview2 = new WebView({
  title: "Multiple deno_webview example",
  url: `data:text/html,${encodeURIComponent(html(2))}`,
  width: 400,
  height: 200,
  resizable: true,
  debug: true,
  frameless: false,
});

await Promise.all([webview1.run(), webview2.run()]);
```
log:
```
Download https://deno.land/x/checksum@1.4.0/md5.ts
Download https://deno.land/std@v0.51.0/path/_constants.ts
Download https://deno.land/std@v0.51.0/path/_util.ts
Download https://deno.land/std@v0.51.0/path/_globrex.ts
Download https://deno.land/std@v0.51.0/fmt/colors.ts
Download https://deno.land/std@v0.51.0/testing/diff.ts
...
Compile file:///Users/wangyu/Desktop/workspace/deno-demo/webview.ts
INFO load deno plugin "deno_webview" from local "/Users/wangyu/Desktop/workspace/deno-demo/.deno_plugins/deno_webview_691b9df6ac6b996c9adc4b88a87bd40f.dylib"
[1]    3941 bus error  deno run -A -r --unstable --allow-read webview.ts
```
deno Unexpected exit

**Comment by eliassjogreen** [comment] 2020-06-06 13:14
Closing as it is probably a duplicate of #30

**Closed by eliassjogreen** 2020-06-06 13:14 UTC
